### ISSUE TITLE
[R3] Kubernetes Feasibility Study

### ISSUE THREAD

**Issue by Johnny850807** [Judge-Girl/Judge-K8S#3]
#  Kubernetes Feasibility Study

Kuberenetes Feasibility Study is required prior to entering the next milestone.
Every member should take a deep research on Kubernetes in order to answer the following questions. (The answer of each question should be documented in the same file.)

(The question list can be updated or enriched)

- [x] What / Why / How does K8S schedule a container?
- [x] What can you config related to 'nodes' in K8S?
- [x] What does K8S provide for GPU scheduling?
- [x] How to integrate a program with K8S, on the other hand, how does a program interacts with K8S?

**Comment by haribo0915** [comment]
https://hackmd.io/@YQjF5xybQX6y6JiEuggcbQ/rkTptpNBL
