### ISSUE TITLE
[R4] Research into current legacy Judge Girl System

### ISSUE THREAD

**Issue by Johnny850807** [Judge-Girl/Judge-K8S#4]
# Research into current legacy Judge Girl System

Judge-K8S should provide a **login** function, which would be better if we can integrate with the legacy Judge Girl's login API.

There are more other potentials that we may benefit from the legacy code, no need to reinvent the wheels. Hence this issues targets on such potentials and so take research into it.

The research result will be included in the '[R2] OOA / D' document.

**Comment by Daniel1147** [comment]
I added an API for verifying username and password to legacy system.

**Comment by Johnny850807** [comment]
@Daniel1147 The issue should not be closed, since we haven't documented the result of this feasibility study.
