### ISSUE TITLE
[R5] Code-Judge feasibility study

### ISSUE THREAD

**Issue by Johnny850807** [Judge-Girl/Judge-K8S#5]
# Code-Judge feasibility study

For juding the code submitted, this issue performs a feasibility study for eliciting all practical mechanisms to judge a code, or namely, to **execute a code in the sandbox securely**.

Whether we have to reinventing a wheel, or just apply the current existing solution?

The study result is included in the '[R2] OOA/D' document

**Comment by haribo0915** [comment]
[QingdaoOnlineJudge](https://github.com/QingdaoU/OnlineJudge)
[DMOJ](https://github.com/DMOJ)
[DOMJudge](http://domjudge.org)
[Others](https://codeforces.com/blog/entry/16586)

**Comment by Johnny850807** [comment]
Container-judge seems working like a charm, the overhead is considered small.
